DEVICE : 'cuda'
SEED_VALUE : 4321
LOGDIR : ''
EXP_NAME : 'no'
DEBUG : True 
OUTPUT_DIR : 'results' 
DOWN_DIM: 14

DATASET_NAME : ''
ESTIMATOR : ''
BODY_REPRESENTATION : ''

SMPL_MODEL_DIR : "data/smpl/"

CUDNN :
  BENCHMARK : True
  DETERMINISTIC : False
  ENABLED : True

SEARCH:
  INDEX: 1

MODEL :
  d_word_vec: 128
  d_model: 128
  d_inner: 128
  n_layers: 5
  n_head: 5
  d_k: 64
  d_v: 64
  persons: 1
  slide_window_size: 8

TRAIN :
  BATCH_SIZE : 8000
  WORKERS_NUM : 7
  EPOCH : 30
  LR : 0.001 
  LRDECAY : 0.9
  RESUME : None
  VALIDATE : True
  USE_6D_SMPL : True
  # noise_std : 100
  # noise_type: uniform
  noise_type: gaussian
  noise_std : 10

EVALUATE :
  PRETRAINED : ''
  ROOT_RELATIVE : True
  SLIDE_WINDOW_STEP_SIZE : 1
LOSS :
  W_POS : 1.0
  W_ACCEL : 1.0
  # W_ACCEL : 0.1
LOG :
  NAME : ''
# VIS :
#   END: 100
